Add exception to bounds catch for l.crs.simple
publiclab/Leaflet.DistortableImage pull request #1033
Opened 2022-09-29 07:54 UTC by Aman-Jamshed

added exemption for L.CRS.Simple to _cornerExceedsMapLats()

Fixes #1032  (<=== Add issue number here)
Fixes #1007

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-09-30 13:23 UTC, Aman-Jamshed commented
@jywarren Please check and let me know if something is wrong?

2022-09-30 20:49 UTC, jywarren approved these changes
This looks perfect. Thanks so much!!!

2022-09-30 20:54 UTC, jywarren requested changes
Can you try making these small adjustments, and one more thing - can you try running `grunt build` to compile the code, and then `git add dist/` to add the compiled files? That should complete this PR! ✨✨

2022-09-30 20:54 UTC, jywarren commented on src/DistortableImageOverlay.js
> +    } else {
Aha, it's complaining in the automatic tests about trailing spaces. Try this quick fix!

```suggestion
    } else {
```

2022-09-30 20:54 UTC, jywarren commented on src/DistortableImageOverlay.js
> +      return (exceedsTop || exceedsBottom);
```suggestion
      return (exceedsTop || exceedsBottom);
```

Here too. It's quite picky about formatting!

2022-09-30 20:54 UTC, jywarren commented
Great work!

2022-10-01 22:38 UTC, jywarren approved these changes

2022-10-01 23:11 UTC, jywarren commented
Hi, i wanted to show how to add the dist files -- actually in GitPod, they're automatically built when you start up the gitpod environment -- using the link in the comment above, or https://gitpod.io#https://github.com/publiclab/Leaflet.DistortableImage/pull/1033.

You have to add it with `git add dist` OR click the little `+` button in the "Source Control" sidebar tab in Gitpod:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/24359/193431493-5bac8183-bc44-403a-a61c-ad5dde2a2329.png">

Then commit that. It contains the compiled version of the changes you'd made in the `/src/` directory. 

I'm going to go ahead and do it this time just to merge this! Thank you!

2022-10-01 23:51 UTC, merged

2022-10-01 23:55 UTC, jywarren commented
Great work @Aman-Jamshed -- thank you!

2022-10-02 07:07 UTC, Aman-Jamshed commented
Hey @jywarren Thankyou so much for guidance...Actually I was trying running the command ```grunt build``` as you said earlier to compile the code and I was getting grunt command not found. So I was trying to find its solution. Thanks for letting me know how its done in Gitpod. This is my first time using Gitpod. 

Could you please tell me what to do next?  I'm willing to contribute more and learn about this project.

2022-10-04 16:38 UTC, Aman-Jamshed commented
@jywarren Please respond. It will be very kind of you!

2022-10-04 17:19 UTC, themacboy commented
https://gruntjs.com/getting-started

Try this to install grunt as global:

npm install -g grunt-cli

2022-10-05 10:52 UTC, jywarren commented
Hi @Aman-Jamshed i'm sorry I have been traveling so I missed this! The command is actually not `grunt build` but `npm run setup` -- sorry I messed that up. You can read more about how to set up the project here: https://github.com/publiclab/Leaflet.DistortableImage/blob/main/CONTRIBUTING.md#setup

Thank you very much @themacboy as well!