Update EditAction.js
publiclab/Leaflet.DistortableImage pull request #1055
Opened 2022-10-03 08:58 UTC by M1racle04

Hi this issue was reserved for me and I have done the necessary changes

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-03 09:41 UTC, TildaDares requested changes
Hi @M1racle04, feel free to just click the `Commit Suggestion` button.

2022-10-03 09:41 UTC, TildaDares commented on src/edit/actions/EditAction.js
> + _disableAction() {
```suggestion
  _disableAction() {
```

2022-10-03 09:41 UTC, TildaDares commented on src/edit/actions/EditAction.js
> + _injectIconSet() {
```suggestion
  _injectIconSet() {
```

2022-10-03 09:44 UTC, TildaDares approved these changes
Great work @M1racle04. Thank you!!

2022-10-04 16:15 UTC, merged

2022-10-04 19:31 UTC, M1racle04 commented
Thank You so much