fix: fixed error in the file
publiclab/Leaflet.DistortableImage pull request #1074
Opened 2022-10-09 09:18 UTC by Khadeeejah

Fixes #1066 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-09 09:21 UTC, Khadeeejah commented
hi @TildaDares  kindly review my pr , thank you

2022-10-09 09:30 UTC, TildaDares requested changes
Hi @Khadeeejah, it seems you have a formatter/linter configured in your IDE. Please turn it off so it doesn’t add unwanted changes. Thank you!

2022-10-09 09:30 UTC, TildaDares commented on src/iconsets/IconSet.js
> -    return this._svg;
Hi @Khadeeejah, please undo this change.

2022-10-09 09:30 UTC, TildaDares commented on src/iconsets/IconSet.js
> -    this.addSymbols(this._symbols);
Please undo this change!

2022-10-09 09:30 UTC, TildaDares commented on src/iconsets/IconSet.js
> -    this._svg += symbols;
Please undo this change

2022-10-09 09:30 UTC, TildaDares commented on src/iconsets/IconSet.js
> -});
Please undo this change!

2022-10-09 09:30 UTC, TildaDares commented on src/iconsets/IconSet.js
> -
Please undo this change!

2022-10-09 09:30 UTC, TildaDares commented on src/iconsets/IconSet.js
> -* we don't use it directly */
Please undo this change!

2022-10-09 09:47 UTC, Khadeeejah commented
Hi @TildaDares  sorry about the linter issue, i have fixed the issues

2022-10-09 09:47 UTC, TildaDares approved these changes
Amazing work @Khadeeejah. Thank you!!

2022-10-09 09:49 UTC, merged

2022-10-09 09:49 UTC, TildaDares commented
Congratulations on merging your PR @Khadeeejah 🎉

2022-10-09 11:24 UTC, jywarren commented
Great job!!

2022-10-10 09:12 UTC, Khadeeejah commented
Hi can i start creating new issues for first timers or look for more issues to work on as i am willing to work on more @TildaDares

2022-10-10 09:37 UTC, TildaDares commented
Hi @Khadeeejah, the choice is up to you but it would be very helpful if you could help create issues for other first timers. Thank you!