Update RotateAction.js
publiclab/Leaflet.DistortableImage pull request #1087
Opened 2022-10-10 22:45 UTC by titiodus

Changed var edit to let edit. I chose let over const because of the variable name edit - as this connotes changes is expected.

Hope my PR is accepted and merged.

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-11 23:27 UTC, jywarren commented
Hello, thank you for your contribution, what issue is this for, can you please link to it? Are you sure someone else has not already claimed it? Thank you!

2022-10-12 06:45 UTC, TildaDares requested changes
Hi @titiodus, feel free to just click the `Commit Suggestion` button. Thank you!

2022-10-12 06:45 UTC, TildaDares commented on src/edit/actions/RotateAction.js
> +    let edit = this._overlay.editing;
```suggestion
    const edit = this._overlay.editing;
```

2022-10-12 16:51 UTC, titiodus commented
@TildaDares I have done so. Thanks

2022-10-12 17:21 UTC, TildaDares approved these changes
Amazing work @titiodus. Thank you!

2022-10-12 17:23 UTC, merged

2022-10-12 17:23 UTC, TildaDares commented
Congratulations on merging your PR @titiodus 🎉

2022-10-12 20:24 UTC, titiodus commented
Thank you @TildaDares. I am willing to do more. I can coordinate contributors and such. I am alao available to handle any other issues.