replace var with let/const where appropriate.
publiclab/Leaflet.DistortableImage pull request #1091
Opened 2022-10-10 23:33 UTC by dayopius

Fixes #0000 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-10 23:35 UTC, dayopius commented
@TildaDares

2022-10-11 08:13 UTC, TildaDares approved these changes
Great work @dayopius. Thank you!!

2022-10-13 07:11 UTC, TildaDares requested changes
Feel free to just click the `Commit Suggestion` buttons @dayopius

2022-10-13 07:11 UTC, TildaDares commented on src/edit/actions/DistortAction.js
> +    L.DistortableImage.action_map.d = "_distortMode";
```suggestion
    L.DistortableImage.action_map.d = '_distortMode';
```

2022-10-13 07:11 UTC, TildaDares commented on src/edit/actions/DistortAction.js
> +      className: "distort",
```suggestion
      className: 'distort',
```

2022-10-13 07:11 UTC, TildaDares commented on src/edit/actions/DistortAction.js
> +      html: "distort",
```suggestion
      html: 'distort',
```

2022-10-25 06:28 UTC, TildaDares approved these changes
Amazing work @dayopius. Thank you!

2022-10-25 06:28 UTC, merged