fix: var to let or const（#610）
publiclab/Leaflet.DistortableImage pull request #1103
Opened 2022-10-11 04:16 UTC by xiaodaiweiwei

Fixes #610 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [✅ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ✅] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ✅] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [✅] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-11 06:48 UTC, xiaodaiweiwei commented
@TildaDares I would appreciate a review of my PR. Thanks!

2022-10-11 07:32 UTC, TildaDares requested changes
Hi @xiaodaiweiwei, it seems your IDE added additional files. Can you please remove them? Thanks!

2022-10-11 07:35 UTC, TildaDares requested changes
Hi @xiaodaiweiwei, let's use `const` instead since the variables aren't changing. Thanks!

2022-10-11 07:35 UTC, TildaDares commented on src/util/IconUtil.js
> +    let svg = container.querySelector('svg');
```suggestion
    const svg = container.querySelector('svg');
```

2022-10-11 07:36 UTC, xiaodaiweiwei commented on src/util/IconUtil.js
> +    let svg = container.querySelector('svg');
Ok! I would change that!

2022-10-11 07:49 UTC, xiaodaiweiwei commented
I have made the changes. Please check them. Thank you @TildaDares

2022-10-12 06:40 UTC, TildaDares commented
Hi @xiaodaiweiwei, you can try closing this PR and opening a PR to remove those files. Thanks!

2022-10-12 07:27 UTC, closed without merging