Update DragAction.js
publiclab/Leaflet.DistortableImage pull request #1104
Opened 2022-10-11 05:58 UTC by belfarz

Fixes #504  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-11 22:44 UTC, PeculiarE requested changes

2022-10-11 22:44 UTC, PeculiarE commented on src/edit/actions/DragAction.js
> +    let edit = this._overlay.editing;
Use the 'const' keyword instead.

2022-10-11 22:46 UTC, PeculiarE commented
One more thing, please link the PR to the original issue. Currently, you're linking the PR to itself.

2022-10-11 23:28 UTC, jywarren commented
Hi @PeculiarE thank you so much for helping out! Thanks @belfarz for your contribution!

2022-10-12 05:16 UTC, belfarz commented
hello, Thanks for the corrections but were can i get the link to the
original issue im kinda lost and cant find it

On Tue, 11 Oct 2022 at 23:46, Peculiar Erhisohwode ***@***.***>
wrote:

> One more thing, please link the PR to the original issue. Currently,
> you're linking the PR to itself.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/publiclab/Leaflet.DistortableImage/pull/1104#issuecomment-1275365469>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3OGLH2R7V23PGTEPERUK2LWCXU4RANCNFSM6AAAAAARB5UJIU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-12 05:42 UTC, belfarz commented
> Hi @PeculiarE thank you so much for helping out! Thanks @belfarz for your contribution!

2022-10-12 08:48 UTC, PeculiarE approved these changes
Well done! @belfarz...this looks ready for merging.

@TildaDares....please assist to merge. Thank you!

2022-10-12 10:46 UTC, merged