changed some variable declarations in Leaflet.DistortableImage/src/components/DistortableImage.Keymapper.js
publiclab/Leaflet.DistortableImage pull request #1123
Opened 2022-10-11 22:21 UTC by jesutobi

@TildaDares I have fixed the issues in  ..... Fixes #1086 
[https://github.com/publiclab/Leaflet.DistortableImage/issues/1086](url).

in this directory Leaflet.DistortableImage/src/components/DistortableImage.Keymapper.js 
I changed the variable declaration on line 42 from "var" to const 
I changed the variable declaration on line 45 from "var" to let 
I changed the variable declaration on line 52 from "var" to const 
I changed the variable declaration on line 66 from "var" to const 
I changed the variable declaration on line 131 from "var" to const

2022-10-11 23:56 UTC, PeculiarE requested changes
Hi @jesutobi....thank you for working on this. Could you please undo the changes in the `leaflet.distortableimage.js` file. Only the `DistortableImage.Keymapper.js` file should be changed. Thank you!

2022-10-12 01:04 UTC, jesutobi commented
@PeculiarE i have done it as you requested

2022-10-12 08:58 UTC, PeculiarE requested changes

2022-10-12 08:58 UTC, PeculiarE commented on src/components/DistortableImage.Keymapper.js
> +    let divider = L.DomUtil.create('br', 'divider');
```suggestion
    const divider = L.DomUtil.create('br', 'divider');
```

2022-10-12 09:01 UTC, PeculiarE commented
Hi @jesutobi....please accept and commit the suggested changes by clicking on the `Commit suggestion` button in the review above.

Once this is done, your PR will be ready to merge.


Thank you, and great work so far!

2022-10-12 12:45 UTC, jesutobi commented
@PeculiarE thank you, i have  added the suggested change

2022-10-12 17:53 UTC, PeculiarE requested changes

2022-10-12 17:53 UTC, PeculiarE commented on src/components/DistortableImage.Keymapper.js
> +   const el = L.DomUtil.create('div', '');
```suggestion
    const el = L.DomUtil.create('div', '');
```

2022-10-12 17:56 UTC, PeculiarE commented
Thank you @jesutobi...but the build is failing due to indentation issues. An extra space was omitted in the initial commit.

So, once again, please accept and commit the suggested change by clicking on the Commit suggestion button in the review above, and then we can merge 😄

2022-10-12 20:43 UTC, jesutobi commented
@PeculiarE thank you, i am sorry for the many bugs 😥, i just commited the suggested  changes

2022-10-12 21:13 UTC, PeculiarE commented
It's okay @jesutobi....thanks for sticking with it ❤️

2022-10-12 21:15 UTC, jesutobi commented
@PeculiarE, i still see the "merging is blocked" is there something else i didnt take note off ?

2022-10-12 21:16 UTC, PeculiarE approved these changes
Well done once again! @jesutobi

@TildaDares ....this is ready to merge. Thank you!

2022-10-12 21:17 UTC, PeculiarE commented
> @PeculiarE, i still see the "merging is blocked" is there something else i didnt take note off ?

Oh, don't worry about it. Merging can only be done by those with the appropriate repo permissions

2022-10-12 21:18 UTC, jesutobi commented
> It's okay @jesutobi....thanks for sticking with it ❤️

thanks you

2022-10-12 21:18 UTC, jesutobi commented
> It's okay @jesutobi....thanks for sticking with it ❤️

thanks you

2022-10-12 21:19 UTC, jesutobi commented
> > @PeculiarE, i still see the "merging is blocked" is there something else i didnt take note off ?
> 
> Oh, don't worry about it. Merging can only be done by those with the appropriate repo permissions

okay

2022-10-12 21:42 UTC, merged

2022-10-12 21:42 UTC, TildaDares commented
Congratulations on merging your PR @jesutobi 🎉

2022-10-12 21:43 UTC, TildaDares commented
Thank you for the reviews @PeculiarE!

2022-10-12 21:44 UTC, 7malikk commented
Congratulations @jesutobi 🎊

2022-10-12 21:59 UTC, jesutobi commented
> Congratulations on merging your PR @jesutobi 🎉

thank you :)

2022-10-12 22:00 UTC, jesutobi commented
> Congratulations @jesutobi 🎊

thanks