Modified function getCmPerPixel to es6 funcion in src/util/ImageUtil.js
publiclab/Leaflet.DistortableImage pull request #1164
Opened 2022-10-15 09:52 UTC by kabuur

Fixes #598 (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updates
* [ ] @mention the original creator of the issue in a comment below for help or for a review

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

2022-10-15 10:17 UTC, kabuur commented
Modified function getCmPerPixel to es6 funcion in src/util/ImageUtil.js #1164

2022-10-15 10:36 UTC, TildaDares commented
Hi @kabuur, the function is fine as it is. You don’t have to change it to an ES6 function. Thank you!

2022-10-15 10:38 UTC, TildaDares commented
You are only supposed to change the `var` keyword to `let/const`. Please take a look at the issue description to know the change required https://github.com/publiclab/Leaflet.DistortableImage/issues/1086

2022-10-15 11:36 UTC, TildaDares requested changes

2022-10-15 11:36 UTC, TildaDares commented on src/util/ImageUtil.js
> +  getCmPerPixel:((overlay) =>{
Hi @kabuur, please revert this change.

2022-10-15 11:36 UTC, TildaDares commented on src/util/ImageUtil.js
> +  }),
```suggestion
  },
```

2022-10-15 16:13 UTC, TildaDares commented on src/util/ImageUtil.js
> +  getCmPerPixel:((overlay) =>{
Hi @kabuur, this has not been resolved.

2022-10-15 16:14 UTC, TildaDares commented on src/util/ImageUtil.js
> +  }),
@kabuur Please revert these changes and leave only the `var` keyword change. Thanks!

2022-12-29 02:22 UTC, sashadev-sky commented
Hi! Sorry about this, but we close FTOs with no updates or replies because we assume they have been abandoned. This is to give other contributors a change, as these types of issues are high in demand now. 

If you'd like to try again with a new FTO, we welcome you to!

2022-12-29 02:22 UTC, closed without merging